// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2dJMBB8a6LI6-x08e-zCX4FsUESBiwY',
    appId: '1:408681623035:web:fcdda638bac10e0d0e6f5e',
    messagingSenderId: '408681623035',
    projectId: 'sabdaapp-2d974',
    authDomain: 'sabdaapp-2d974.firebaseapp.com',
    storageBucket: 'sabdaapp-2d974.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmzD1xxKvrrQ7sXGvfyVtkUBYCClysjqc',
    appId: '1:408681623035:android:9375c2db04c48daf0e6f5e',
    messagingSenderId: '408681623035',
    projectId: 'sabdaapp-2d974',
    storageBucket: 'sabdaapp-2d974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeVbe1B5BW8jgCPUQJLnBe3x9f9RR24DE',
    appId: '1:408681623035:ios:796b15d5ef289f430e6f5e',
    messagingSenderId: '408681623035',
    projectId: 'sabdaapp-2d974',
    storageBucket: 'sabdaapp-2d974.firebasestorage.app',
    iosBundleId: 'com.app.flutter5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeVbe1B5BW8jgCPUQJLnBe3x9f9RR24DE',
    appId: '1:408681623035:ios:796b15d5ef289f430e6f5e',
    messagingSenderId: '408681623035',
    projectId: 'sabdaapp-2d974',
    storageBucket: 'sabdaapp-2d974.firebasestorage.app',
    iosBundleId: 'com.app.flutter5a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh2dJMBB8a6LI6-x08e-zCX4FsUESBiwY',
    appId: '1:408681623035:web:9f2f9e04b1a197610e6f5e',
    messagingSenderId: '408681623035',
    projectId: 'sabdaapp-2d974',
    authDomain: 'sabdaapp-2d974.firebaseapp.com',
    storageBucket: 'sabdaapp-2d974.firebasestorage.app',
  );
}
